/**
 * MODULE: Localization
 * Manages UI text translation based on the selected language.
 */
export class Localization {
    constructor() {
        this.translations = {
            en: {
                // General UI
                "appTitle": "ATDS Health & Breath Analyzer",
                "subtitle": "Bio-Metric Analysis System",
                "statusReady": "Ready",
                "noDeviceConnected": "No Device Connected (File Mode)",
                "signal": "Signal:",
                "signalExcellent": "Excellent",
                "signalWeak": "Weak Signal",
                "signalNoSignal": "No Signal",
                "sensorOffSkin": "Sensor Off Skin",
                "loadData": "Load Data",
                "loadDataTooltip": "Supports .txt (raw RR intervals) or .atds (JSON session data)",
                "weight": "Weight",
                "age": "Age",
                "gender": "Gender",
                "male": "Male",
                "female": "Female",
                "deviceConnection": "Device Connection",
                "connectUSBDongle": "Connect USB Dongle",
                "connectBluetoothLE": "Connect Bluetooth LE",
                "generateReport": "Generate Report",
                "generateReportTooltip": "Process the loaded file and generate charts",
                "analyzeChart": "Analyze Chart",
                "analyzeChartTooltip": "Enter Data Cleaning Mode to edit points",
                "exitAnalyzeMode": "Exit Analyze Mode",
                "resetZoom": "Reset Zoom",
                "resetZoomTooltip": "Reset chart zoom level",
                "multiView": "Multi-View",
                "multiViewTooltip": "Toggle side-by-side view with Poincaré plot",
                "cropToView": "Crop to View",
                "cropToViewTooltip": "Crop data to current zoomed view",
                "saveATDS": "Save ATDS",
                "saveATDSTooltip": "Save current session as .atds (JSON)",
                "saveTXT": "Save TXT",
                "saveTXTTooltip": "Export raw RR intervals as .txt",
                "saveExcel": "Save Excel",
                "saveExcelTooltip": "Export analysis summary and data as .csv",
                "exportPDF": "Export PDF",
                "exportPDFTooltip": "Download report as PDF",
                "copyText": "Copy Text",
                "copyTextTooltip": "Copy summary text to clipboard",
                "settings": "Settings",
                "preferences": "Preferences",
                "weightUnit": "Weight Unit",
                "kilograms": "Kilograms (kg)",
                "pounds": "Pounds (lbs)",
                "deviceProtocol": "Device Protocol",
                "usbSerial": "USB Serial (BM-USBCDC)",
                "bluetoothLE": "Bluetooth LE (BlueRobin)",
                "language": "Language",
                "english": "English",
                "dutch": "Dutch (Nederlands)",
                "german": "German (Deutsch)",
                "french": "French (Français)",
                "connectedDeviceFW": "Connected Device FW",
                "savePreferences": "Save Preferences",
                "batteryCritical": "Battery Critical (<5%): Live feed stopped automatically.",
                "noDataToExport": "No data to export.",
                "errorParsingATDS": "Error parsing ATDS file.",
                "invalidRRData": "Error: File contains invalid RR interval data.",
                "noValidRRFound": "Error: No valid RR intervals found in file.",
                "unexpectedError": "An unexpected error occurred during processing.",
                "selectionTooSmall": "Selection too small. Please zoom out to select at least 10 beats.",
                "cropConfirm": "Crop data to currently visible range (Beats {start} to {end})?",
                "atResetConfirm": "AT Reset to Auto-Calculated value: {value} BPM",
                "pleaseLoadFile": "Please load a file first.",
                "editBPM": "Edit BPM for point #{index}:",
                "deletePointConfirm": "Delete point #{index}?",
                "poincareNotGenerated": "Poincaré plot is not generated yet.",
                "histogramNotGenerated": "Histogram chart is not generated yet.",
                "pdfLibraryNotLoaded": "PDF library not loaded.",
                "errorGeneratingPDF": "Error generating PDF",
                "summaryCopied": "Summary copied to clipboard!",
                "stopLiveFeed": "Stop Live Feed",
                "startLiveFeed": "Start Live Feed",
                "bpm": "BPM",
                "ms": "ms",
                "brMin": "Breaths/Min",
                "mlKgMin": "ml/kg/min",
                "liveMetabolicRate": "Live Metabolic Rate",
                "analysisFor": "Analysis for a <strong>{age}-year-old {gender}</strong>:",
                "hrvAmplitude": "<strong>HRV Amplitude:</strong> {value}ms ({class} for age group).",
                "sdnnRmssd": "<strong>SDNN / RMSSD:</strong> {sdnn}ms / {rmssd}ms.",
                "vo2MaxEstimate": "<strong>VO2 Max Estimate:</strong> {value} ml/kg/min ({class}).",
                "breathRate": "<strong>Breath Rate:</strong> {value} bpm ({class}).",
                "analysisSummary": "Analysis Summary",
                "trainingZones": "Training Zones (Estimated)",
                "zone": "Zone",
                "rangeBPM": "Range (BPM)",
                "description": "Description",
                "recovery": "Recovery",
                "recoveryDesc": "Active recovery, very light effort",
                "aerobic": "Aerobic",
                "aerobicDesc": "Endurance building, conversation pace",
                "tempo": "Tempo",
                "tempoDesc": "Rhythm, sustainable fast pace",
                "threshold": "Threshold",
                "thresholdDesc": "Lactate Threshold, hard effort",
                "anaerobic": "Anaerobic",
                "anaerobicDesc": "Intervals, maximum effort",
                "avgHeartRate": "Avg Heart Rate",
                "tiTeRatio": "Ti / Te Ratio",
                "tiTeDesc": "Inhalation Time divided by Exhalation Time. >1 means longer inhale.",
                "hrvAmplitudeShort": "HRV Amplitude",
                "hrvAmplitudeDesc": "Average difference between min and max heart rate during a breath cycle (RSA)",
                "vo2MaxEst": "VO2 Max Est.",
                "vo2MaxEstDesc": "Estimated oxygen intake capacity",
                "editPoint": "Edit Value",
                "deletePoint": "Delete Point",
                "cancel": "Cancel",
                "point": "Point",
                "filtered": "Filtered",
                "unfiltered": "Unfiltered",
                "raw": "Raw",
                "filteredHR": "Filtered HR (BPM)",
                "unfilteredHR": "Unfiltered HR (BPM)",
                "analyzeModeTitle": "Analyze Mode: Data Cleaning",
                "rsaTitle": "Respiratory Sinus Arrhythmia (RSA)",
                "heartRateBPM": "Heart Rate (BPM)",
                "beatCount": "Beat Count",
                "poincarePlot": "Poincaré (RR_n vs RR_n+1)",
                "rrN": "RR[n] (ms)",
                "rrN1": "RR[n+1] (ms)",
                "frequency": "Frequency",
                "atLine": "AT: {value} BPM (Drag to Adjust)",
                "sessionActions": "Session Actions",
                "selectTask": "-- Select Task --",
                "restTest": "Rest Test (Recovery Focus)",
                "trainingSession": "Training Session (Zone Focus)",
                "exportPDFReport": "Export PDF Report",
                "exportExcelClinical": "Export Excel (Clinical)",
                "openECFAQManual": "Open EC FAQ / Manual",
                "honourStans": "Honour Stans van der Poel",
                "displaySettings": "Display Settings",
                "showZones": "Show Zones",
                "filterOn": "Filter On",
                "showAdvancedCharts": "Show Advanced Charts",
                "bmiDongle": "BMI Dongle (USB)",
                "bluerobinBT": "BlueRobin/BT",
                "firmwareRevision": "Firmware Revision:",
                "batteryLevel": "Battery Level:",
                "serialConnectionError": "Serial Connection Error:",
                "bluetoothConnectionError": "Bluetooth Connection Error:",
                "pairingFailed": "Pairing failed. Please check device bonding.",
                "btConnectionFailed": "Bluetooth connection failed:",
                "webBluetoothNotSupported": "Web Bluetooth API not supported.",
                "webSerialNotSupported": "Web Serial API not supported. Please use Chrome or Edge.",
                "atdsReport": "ATDS Analysis Report",
                "date": "Date",
                "userProfile": "User Profile",
                "ageShort": "Age",
                "weightShort": "Weight",
                "genderShort": "Gender",
                "avgHR": "Avg HR",
                "breathRateShort": "Breath Rate",
                "hrvAmplitudeExcel": "HRV Amplitude",
                "sdnn": "SDNN",
                "rmssd": "RMSSD",
                "vo2MaxEstExcel": "VO2 Max Est.",
                "tiTeRatioExcel": "Ti/Te Ratio",
                "beatData": "Beat Data",
                "index": "Index",
                "rrInterval": "RR Interval (ms)",
                "heartRateBPMExcel": "Heart Rate (BPM)",
                "atdsHealthReportSummary": "ATDS Health Report Summary",
                "avgHeartRateSummary": "Avg Heart Rate:",
                "tiTeRatioSummary": "Ti/Te Ratio:",
                "breathRateSummary": "Breath Rate:",
                "hrvAmplitudeSummary": "HRV Amplitude:",
                "vo2MaxEstSummary": "VO2 Max Est:",
                "summaryCopied": "Summary copied to clipboard!",
                "textBelowEditable": "✎ Text below is editable.",
                "uploadDataToSeeAnalysis": "Upload data to see analysis.",
                "hrvLow": "Low",
                "hrvNormal": "Normal",
                "hrvHigh": "High",
                "brSlow": "Slow",
                "brNormal": "Normal",
                "brFast": "Fast",
                "vo2Poor": "Poor",
                "vo2Fair": "Fair",
                "vo2Good": "Good",
                "vo2Excellent": "Excellent",
                "vo2Superior": "Superior",
                "n_a": "N/A",
                "y": "y",
                "kg": "kg",
                "msRSA": "ms (RSA)",
                "bpmShort": "BPM",
                "mlKgMinShort": "ml/kg/min",
                "msShort": "ms",
                "firmwareType": "firmware",
                "batteryType": "battery",
                "signalType": "signal",
                "editPointTitle": "Point #{index} ({datasetName})",
                "editable": "Editable",
                "smoothed": "Smoothed",
                "stansSubtitle": "Pioneer in Lung Function and Exercise Physiology",
                "courses": "Courses:",
                "coachopleiding": "Coach Opleiding",
                "ademtherapie": "Ademtherapie",
                "specialisaties": "Specialisaties",
                "eliteSportsAchievements": "Elite Sports Achievements:",
                "premierLeagueHollandFootball": "Premier League & Holland Football",
                "iceSkating": "Ice Skating",
                "inventionsDesc": "Developer of multiple devices to test breathing and metabolic load.",
                "hardware": "Hardware",
                "apps": "Apps",
                "patent": "Patent",
                "books": "Books:",
                "mediaBlogs": "📺 Media & Blogs",
                "youtubeVideoFeatures": "YouTube & Video Features:",
                "stansonstressbreathing": "Stans on Stress & Breathing",
                "officialenergycontrolchannel": "Official Energy Control Channel",
                "blogsMentions": "✍️ Blogs & Mentions:",
                "herBlogs": "Her Blogs",
                "latestecinsights": "Latest EC Insights",
                "onextraoxygenintake": "On Extra Oxygen Intake",
                "mentions": "Mentions",
                "sportrustenleermeester": "Sportrusten: Leermeester",
                "biocheckmethodgrounding": "BioCheck: Method Grounding",
                "faqEnergyControlMethod": "❓ FAQ: Energy Control Method",
                "exhaustedWhyExercise": "I am exhausted; why should I exercise?",
                "exhaustedWhyExerciseAnswer": "Chronic fatigue is often caused by an 'idling motor' that burns sugar in rest. Balans-level exercise helps your muscles store more glycogen, eventually doubling your energy reserves.",
                "coldHandsFeet": "Why do my hands and feet feel cold?",
                "coldHandsFeetAnswer": "Low CO2 levels from over-breathing cause blood vessels to constrict. Warming hands/feet during therapy is a primary sign of successful metabolic balance.",
                "noWeightLossImmediately": "What if I don't lose weight immediately?",
                "noWeightLossImmediatelyAnswer": "Muscles that are activated through training require more energy to maintain, even while you sleep. Focus on getting stronger first; the weight loss will follow once the system is 'awake'.",
                "bestTrainingBalance": "What is the best training balance?",
                "bestTrainingBalanceAnswer": "The ideal state is 50% fat and 50% sugar burning, as this is where the body is most in balance—sometimes even more so than in absolute rest.",
                "footerCopyright": "&copy; 2024 ATDS Health & Breath Analyzer. All rights reserved."
            },
            nl: {
                // General UI
                "appTitle": "ATDS Gezondheids- & Ademanalysator",
                "subtitle": "Biometrisch Analysesysteem",
                "statusReady": "Klaar",
                "noDeviceConnected": "Geen apparaat verbonden (Bestandsmodus)",
                "signal": "Signaal:",
                "signalExcellent": "Uitstekend",
                "signalWeak": "Zwak Signaal",
                "signalNoSignal": "Geen Signaal",
                "sensorOffSkin": "Sensor van de huid",
                "loadData": "Gegevens laden",
                "loadDataTooltip": "Ondersteunt .txt (ruwe RR-intervallen) of .atds (JSON-sessiegegevens)",
                "weight": "Gewicht",
                "age": "Leeftijd",
                "gender": "Geslacht",
                "male": "Man",
                "female": "Vrouw",
                "deviceConnection": "Apparaatverbinding",
                "connectUSBDongle": "Verbind USB Dongle",
                "connectBluetoothLE": "Verbind Bluetooth LE",
                "generateReport": "Genereer Rapport",
                "generateReportTooltip": "Verwerk de geladen gegevens en genereer grafieken",
                "analyzeChart": "Analyseer Grafiek",
                "analyzeChartTooltip": "Ga naar de gegevensopschoningsmodus om punten te bewerken",
                "exitAnalyzeMode": "Analysemodus verlaten",
                "resetZoom": "Zoom resetten",
                "resetZoomTooltip": "Reset het zoomniveau van de grafiek",
                "multiView": "Multi-weergave",
                "multiViewTooltip": "Schakel zij-aan-zij weergave met Poincaré-plot",
                "cropToView": "Bijsnijden naar weergave",
                "cropToViewTooltip": "Snijd gegevens bij tot het huidige zichtbare bereik",
                "saveATDS": "Sla ATDS op",
                "saveATDSTooltip": "Sla de huidige sessie op als .atds (JSON)",
                "saveTXT": "Sla TXT op",
                "saveTXTTooltip": "Exporteer ruwe RR-intervallen als .txt",
                "saveExcel": "Sla Excel op",
                "saveExcelTooltip": "Exporteer analysesamenvatting en gegevens als .csv",
                "exportPDF": "Exporteer PDF",
                "exportPDFTooltip": "Download rapport als PDF",
                "copyText": "Kopieer Tekst",
                "copyTextTooltip": "Kopieer samenvatting naar klembord",
                "settings": "Instellingen",
                "preferences": "Voorkeuren",
                "weightUnit": "Gewichtseenheid",
                "kilograms": "Kilogram (kg)",
                "pounds": "Pond (lbs)",
                "deviceProtocol": "Apparaatprotocol",
                "usbSerial": "USB Serieel (BM-USBCDC)",
                "bluetoothLE": "Bluetooth LE (BlueRobin)",
                "language": "Taal",
                "english": "Engels",
                "dutch": "Nederlands",
                "german": "Duits",
                "french": "Frans",
                "connectedDeviceFW": "Verbonden Apparaat FW",
                "savePreferences": "Voorkeuren opslaan",
                "batteryCritical": "Batterij kritiek (<5%): Live feed automatisch gestopt.",
                "noDataToExport": "Geen gegevens om te exporteren.",
                "errorParsingATDS": "Fout bij het parseren van het ATDS-bestand.",
                "invalidRRData": "Fout: Bestand bevat ongeldige RR-intervalgegevens.",
                "noValidRRFound": "Fout: Geen geldige RR-intervallen gevonden in bestand.",
                "unexpectedError": "Er is een onverwachte fout opgetreden tijdens de verwerking.",
                "selectionTooSmall": "Selectie te klein. Zoom uit om minimaal 10 slagen te selecteren.",
                "cropConfirm": "Gegevens bijsnijden tot het huidige zichtbare bereik (Slagen {start} tot {end})?",
                "atResetConfirm": "AT gereset naar automatisch berekende waarde: {value} BPM",
                "pleaseLoadFile": "Laad eerst een bestand.",
                "editBPM": "BPM bewerken voor punt #{index}:",
                "deletePointConfirm": "Punt #{index} verwijderen?",
                "poincareNotGenerated": "Poincaré-plot is nog niet gegenereerd.",
                "histogramNotGenerated": "Histogram is nog niet gegenereerd.",
                "pdfLibraryNotLoaded": "PDF-bibliotheek niet geladen.",
                "errorGeneratingPDF": "Fout bij het genereren van PDF",
                "summaryCopied": "Samenvatting gekopieerd naar klembord!",
                "stopLiveFeed": "Stop Live Feed",
                "startLiveFeed": "Start Live Feed",
                "bpm": "BPM",
                "ms": "ms",
                "brMin": "Ademhalingen/Min",
                "mlKgMin": "ml/kg/min",
                "liveMetabolicRate": "Live Metabolische Snelheid",
                "analysisFor": "Analyse voor een <strong>{age}-jarige {gender}</strong>:",
                "hrvAmplitude": "<strong>HRV Amplitude:</strong> {value}ms ({class} voor leeftijdsgroep).",
                "sdnnRmssd": "<strong>SDNN / RMSSD:</strong> {sdnn}ms / {rmssd}ms.",
                "vo2MaxEstimate": "<strong>VO2 Max Schatting:</strong> {value} ml/kg/min ({class}).",
                "breathRate": "<strong>Ademhalingsfrequentie:</strong> {value} bpm ({class}).",
                "analysisSummary": "Analyse Samenvatting",
                "trainingZones": "Trainingszones (Geschat)",
                "zone": "Zone",
                "rangeBPM": "Bereik (BPM)",
                "description": "Beschrijving",
                "recovery": "Herstel",
                "recoveryDesc": "Actief herstel, zeer lichte inspanning",
                "aerobic": "Aeroob",
                "aerobicDesc": "Uithoudingsvermogen opbouwen, gespreksritme",
                "tempo": "Tempo",
                "tempoDesc": "Ritme, duurzaam snel tempo",
                "threshold": "Drempel",
                "thresholdDesc": "Lactaatdrempel, zware inspanning",
                "anaerobic": "Anaeroob",
                "anaerobicDesc": "Intervallen, maximale inspanning",
                "avgHeartRate": "Gem. Hartslag",
                "tiTeRatio": "Ti / Te Verhouding",
                "tiTeDesc": "Inademtijd gedeeld door uitademtijd. >1 betekent langere inademing.",
                "hrvAmplitudeShort": "HRV Amplitude",
                "hrvAmplitudeDesc": "Gemiddeld verschil tussen min en max hartslag tijdens een ademhalingscyclus (RSA)",
                "vo2MaxEst": "VO2 Max Schatting",
                "vo2MaxEstDesc": "Geschatte zuurstofopnamecapaciteit",
                "editPoint": "Waarde bewerken",
                "deletePoint": "Punt verwijderen",
                "cancel": "Annuleren",
                "point": "Punt",
                "filtered": "Gefilterd",
                "unfiltered": "Ongefilterd",
                "raw": "Ruwe gegevens",
                "filteredHR": "Gefilterde HS (BPM)",
                "unfilteredHR": "Ongefilterde HS (BPM)",
                "analyzeModeTitle": "Analysemodus: Gegevens opschonen",
                "rsaTitle": "Respiratoire Sinus Aritmie (RSA)",
                "heartRateBPM": "Hartslag (BPM)",
                "beatCount": "Slagen telling",
                "poincarePlot": "Poincaré (RR_n vs RR_n+1)",
                "rrN": "RR[n] (ms)",
                "rrN1": "RR[n+1] (ms)",
                "frequency": "Frequentie",
                "atLine": "AT: {value} BPM (Slepen om aan te passen)",
                "sessionActions": "Sessie Acties",
                "selectTask": "-- Selecteer Taak --",
                "restTest": "Rusttest (Herstelfocus)",
                "trainingSession": "Trainingssessie (Zonefocus)",
                "exportPDFReport": "Exporteer PDF Rapport",
                "exportExcelClinical": "Exporteer Excel (Klinisch)",
                "openECFAQManual": "Open EC FAQ / Handleiding",
                "honourStans": "Eerbetoon Stans van der Poel",
                "displaySettings": "Weergave-instellingen",
                "showZones": "Toon Zones",
                "filterOn": "Filter Aan",
                "showAdvancedCharts": "Toon Geavanceerde Grafieken",
                "bmiDongle": "BMI Dongle (USB)",
                "bluerobinBT": "BlueRobin/BT",
                "firmwareRevision": "Firmware Revisie:",
                "batteryLevel": "Batterijniveau:",
                "serialConnectionError": "Seriële Verbindingsfout:",
                "bluetoothConnectionError": "Bluetooth Verbindingsfout:",
                "pairingFailed": "Koppelen mislukt. Controleer apparaatkoppeling.",
                "btConnectionFailed": "Bluetooth verbinding mislukt:",
                "webBluetoothNotSupported": "Web Bluetooth API niet ondersteund.",
                "webSerialNotSupported": "Web Serial API niet ondersteund. Gebruik Chrome of Edge.",
                "atdsReport": "ATDS Analyserapport",
                "date": "Datum",
                "userProfile": "Gebruikersprofiel",
                "ageShort": "Leeftijd",
                "weightShort": "Gewicht",
                "genderShort": "Geslacht",
                "avgHR": "Gem. HS",
                "breathRateShort": "Ademh. Freq.",
                "hrvAmplitudeExcel": "HRV Amplitude",
                "sdnn": "SDNN",
                "rmssd": "RMSSD",
                "vo2MaxEstExcel": "VO2 Max Schat.",
                "tiTeRatioExcel": "Ti/Te Verhouding",
                "beatData": "Slaggegevens",
                "index": "Index",
                "rrInterval": "RR Interval (ms)",
                "heartRateBPMExcel": "Hartslag (BPM)",
                "atdsHealthReportSummary": "ATDS Gezondheidsrapport Samenvatting",
                "avgHeartRateSummary": "Gem. Hartslag:",
                "tiTeRatioSummary": "Ti/Te Verhouding:",
                "breathRateSummary": "Ademhalingsfrequentie:",
                "hrvAmplitudeSummary": "HRV Amplitude:",
                "vo2MaxEstSummary": "VO2 Max Schatting:",
                "summaryCopied": "Samenvatting gekopieerd naar klembord!",
                "textBelowEditable": "✎ Tekst hieronder is bewerkbaar.",
                "uploadDataToSeeAnalysis": "Upload gegevens om analyse te zien.",
                "hrvLow": "Laag",
                "hrvNormal": "Normaal",
                "hrvHigh": "Hoog",
                "brSlow": "Langzaam",
                "brNormal": "Normaal",
                "brFast": "Snel",
                "vo2Poor": "Slecht",
                "vo2Fair": "Redelijk",
                "vo2Good": "Goed",
                "vo2Excellent": "Uitstekend",
                "vo2Superior": "Superieur",
                "n_a": "N.v.t.",
                "y": "j",
                "kg": "kg",
                "msRSA": "ms (RSA)",
                "bpmShort": "BPM",
                "mlKgMinShort": "ml/kg/min",
                "msShort": "ms",
                "firmwareType": "firmware",
                "batteryType": "batterij",
                "signalType": "signaal",
                "editPointTitle": "Punt #{index} ({datasetName})",
                "editable": "Bewerkbaar",
                "smoothed": "Vloeiend",
                "stansSubtitle": "Pionier in Longfunctie en Inspanningsfysiologie",
                "courses": "Cursussen:",
                "coachopleiding": "Coach Opleiding",
                "ademtherapie": "Ademtherapie",
                "specialisaties": "Specialisaties",
                "eliteSportsAchievements": "Elite Sportprestaties:",
                "premierLeagueHollandFootball": "Premier League & Nederlands Voetbal",
                "iceSkating": "Schaatsen",
                "inventionsDesc": "Ontwikkelaar van meerdere apparaten om ademhaling en metabole belasting te testen.",
                "hardware": "Hardware",
                "apps": "Apps",
                "patent": "Octrooi",
                "books": "Boeken:",
                "mediaBlogs": "📺 Media & Blogs",
                "youtubeVideoFeatures": "YouTube & Video Features:",
                "stansonstressbreathing": "Stans over Stress & Ademhaling",
                "officialenergycontrolchannel": "Officieel Energy Control Kanaal",
                "blogsMentions": "✍️ Blogs & Vermeldingen:",
                "herBlogs": "Haar Blogs",
                "latestecinsights": "Laatste EC Inzichten",
                "onextraoxygenintake": "Over Extra Zuurstofopname",
                "mentions": "Vermeldingen",
                "sportrustenleermeester": "Sportrusten: Leermeester",
                "biocheckmethodgrounding": "BioCheck: Methode Grondslag",
                "faqEnergyControlMethod": "❓ FAQ: Energy Control Methode",
                "exhaustedWhyExercise": "Ik ben uitgeput; waarom zou ik sporten?",
                "exhaustedWhyExerciseAnswer": "Chronische vermoeidheid wordt vaak veroorzaakt door een 'stationair draaiende motor' die in rust suiker verbrandt. Balans-niveau oefeningen helpen je spieren meer glycogeen op te slaan, waardoor je energiereserves uiteindelijk verdubbelen.",
                "coldHandsFeet": "Waarom voelen mijn handen en voeten koud aan?",
                "coldHandsFeetAnswer": "Lage CO2-niveaus door over-ademhaling veroorzaken vernauwing van bloedvaten. Warme handen/voeten tijdens therapie is een primair teken van een succesvolle metabole balans.",
                "noWeightLossImmediately": "Wat als ik niet meteen afval?",
                "noWeightLossImmediatelyAnswer": "Spieren die door training worden geactiveerd, hebben meer energie nodig om te onderhouden, zelfs terwijl je slaapt. Concentreer je eerst op sterker worden; het gewichtsverlies volgt zodra het systeem 'wakker' is.",
                "bestTrainingBalance": "Wat is de beste trainingsbalans?",
                "bestTrainingBalanceAnswer": "De ideale toestand is 50% vet- en 50% suikerverbranding, aangezien dit de toestand is waarin het lichaam het meest in balans is - soms zelfs meer dan in absolute rust.",
                "footerCopyright": "&copy; 2024 ATDS Gezondheids- & Ademanalysator. Alle rechten voorbehouden."
            }
            // Add other languages here
        };
        this.currentLang = localStorage.getItem('atds_language') || 'en';
    }

    setLanguage(lang) {
        if (this.translations[lang]) {
            this.currentLang = lang;
            localStorage.setItem('atds_language', lang);
            this.applyTranslations(); // Re-apply translations to the UI
        } else {
            console.warn(`Language '${lang}' not supported. Falling back to 'en'.`);
            this.currentLang = 'en';
            localStorage.setItem('atds_language', 'en');
            this.applyTranslations();
        }
    }

    getLanguage() {
        return this.currentLang;
    }

    translate(key, replacements = {}) {
        let text = this.translations[this.currentLang]?.[key] || this.translations.en[key] || key;
        for (const [placeholder, value] of Object.entries(replacements)) {
            text = text.replace(`{${placeholder}}`, value);
        }
        return text;
    }

    applyTranslations() {
        // Update static text elements with data-i18n attribute
        document.querySelectorAll('[data-i18n]').forEach(element => {
            const key = element.getAttribute('data-i18n');
            let translatedText = this.translate(key);
            
            // Handle suffix for labels like "Weight (kg)"
            const suffix = element.getAttribute('data-i18n-suffix');
            if (suffix) {
                translatedText += ` ${suffix}`;
            }
            element.innerHTML = translatedText;
        });

        // Update tooltips with data-tooltip-i18n attribute
        document.querySelectorAll('[data-tooltip-i18n]').forEach(element => {
            const key = element.getAttribute('data-tooltip-i18n');
            element.setAttribute('data-tooltip', this.translate(key));
        });

        // Update input placeholders with data-i18n-placeholder attribute
        document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
            const key = element.getAttribute('data-i18n-placeholder');
            element.setAttribute('placeholder', this.translate(key));
        });

        // Update select options with data-i18n attribute
        document.querySelectorAll('select option[data-i18n]').forEach(option => {
            const key = option.getAttribute('data-i18n');
            option.innerText = this.translate(key);
        });

        // Update specific elements that need dynamic content or special handling
        // These calls ensure dynamic parts of the UI are re-rendered with the new language.
        if (window.app) {
            if (typeof window.app.refreshChart === 'function') {
                window.app.refreshChart(); // Re-render chart titles, labels, report content etc.
            }
            if (typeof window.app.updateZoneTable === 'function') {
                window.app.updateZoneTable(window.app.session.getAT()); // Re-render zone table
            }
            if (typeof window.app.updateSignalUI === 'function' && window.app.currentSignalQuality) {
                // Re-translate current signal text
                let signalTextKey;
                switch(window.app.currentSignalQuality) {
                    case 'good': signalTextKey = 'signalExcellent'; break;
                    case 'fair': signalTextKey = 'signalWeak'; break;
                    case 'poor': signalTextKey = 'signalNoSignal'; break;
                    case 'poor_contact': signalTextKey = 'sensorOffSkin'; break;
                    default: signalTextKey = ''; break;
                }
                window.app.updateSignalUI(window.app.currentSignalQuality, this.translate(signalTextKey));
            }
            // Re-inject UIManager elements to ensure they are translated
            if (window.app.uiManager) {
                window.app.uiManager.injectExtendedUI(); // Re-injects and translates new inputs
                window.app.uiManager.injectActionMenu(); // Re-injects and translates action menu
                window.app.uiManager.setupToggles(); // Re-injects and translates toggles
            }
        }
    }
}

export const i18n = new Localization();